  # Stage 4: Push Docker image to Amazon ECR
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: vote-docker-image

      - name: Load Docker image
        run: docker load -i vote-image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::573539705056:role/GitHubActions-ECR-EKS
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker tag kenny891/my-vote-app_demo:6.0 573539705056.dkr.ecr.eu-north-1.amazonaws.com/vote-app:6.0
          docker push 573539705056.dkr.ecr.eu-north-1.amazonaws.com/vote-app:6.0